// Mock data matching backend schema
export const internships = [
  {
    id: "1",
    title: "Frontend Development Intern",
    description:
      "We are looking for a passionate Frontend Development Intern to join our dynamic team. You will work on building modern web applications using React and TypeScript.\n\nAs part of our team, you'll collaborate with experienced developers, participate in code reviews, and contribute to real projects that impact thousands of users.",
    skills: ["React", "TypeScript", "Tailwind CSS", "Git"],
    stipend: 15000,
    duration: "3 months",
    internshipType: "Remote",
    openings: 3,
    startDate: "2025-01-15",
    location: "Bangalore",
    isActive: true,
    applications: 45,
    createdAt: "2024-12-09",
    applied: false,
  },
  {
    id: "2",
    title: "Backend Developer Intern",
    description:
      "Join our backend team to build scalable APIs and microservices that power our growing platform.\n\nYou'll work with Node.js, MongoDB, and modern backend technologies to create robust server-side solutions.",
    skills: ["Node.js", "MongoDB", "Express", "REST API"],
    stipend: 20000,
    duration: "6 months",
    internshipType: "Hybrid",
    openings: 2,
    startDate: "2025-02-01",
    location: "Mumbai",
    isActive: true,
    applications: 78,
    createdAt: "2024-12-06",
    applied: true,
  },
  {
    id: "3",
    title: "UI/UX Design Intern",
    description:
      "Help us create beautiful and intuitive user experiences for our clients across various industries.\n\nYou'll be responsible for creating wireframes, prototypes, and high-fidelity mockups while collaborating closely with our development team.",
    skills: ["Figma", "Adobe XD", "Prototyping", "User Research"],
    stipend: 12000,
    duration: "2 months",
    internshipType: "Remote",
    openings: 1,
    startDate: "2025-01-01",
    isActive: true,
    applications: 32,
    createdAt: "2024-12-04",
    applied: false,
  },
  {
    id: "4",
    title: "Data Science Intern",
    description:
      "Work on real-world data science projects and help derive actionable insights from complex datasets.\n\nYou'll analyze large datasets, build machine learning models, and create data visualizations that drive business decisions.",
    skills: ["Python", "Machine Learning", "SQL", "Pandas", "TensorFlow"],
    stipend: 25000,
    duration: "3 months",
    internshipType: "On-site",
    openings: 2,
    startDate: "2025-01-15",
    location: "Hyderabad",
    isActive: true,
    applications: 120,
    createdAt: "2024-12-08",
    applied: false,
  },
  {
    id: "5",
    title: "Marketing Intern",
    description:
      "Join our marketing team to learn digital marketing strategies and help grow our brand presence.\n\nYou'll manage social media accounts, create content, and track marketing metrics to optimize our campaigns.",
    skills: ["Social Media", "Content Writing", "SEO", "Analytics"],
    stipend: 8000,
    duration: "1 month",
    internshipType: "Hybrid",
    openings: 5,
    startDate: "2025-01-01",
    location: "Delhi",
    isActive: true,
    applications: 23,
    createdAt: "2024-12-10",
    applied: false,
  },
  {
    id: "6",
    title: "Mobile App Development Intern",
    description:
      "Build cross-platform mobile applications that reach millions of users worldwide.\n\nYou'll develop mobile applications using React Native, integrate with backend APIs, and optimize app performance.",
    skills: ["React Native", "JavaScript", "Firebase", "Redux"],
    stipend: 18000,
    duration: "4 months",
    internshipType: "Remote",
    openings: 2,
    startDate: "2025-03-01",
    location: "Pune",
    isActive: true,
    applications: 56,
    createdAt: "2024-12-07",
    applied: false,
  },
];